# Generated by Django 5.2.11 on 2026-03-01 06:11

from django.db import migrations


ROLE_MAP = {
    'OWNER': 'owner',
    'ADMIN': 'admin',
    'MEMBER': 'member',
}


def lowercase_roles(apps, schema_editor):
    OrganizationMember = apps.get_model('organizations', 'OrganizationMember')
    for old, new in ROLE_MAP.items():
        OrganizationMember.objects.filter(role=old).update(role=new)


def uppercase_roles(apps, schema_editor):
    OrganizationMember = apps.get_model('organizations', 'OrganizationMember')
    for old, new in ROLE_MAP.items():
        OrganizationMember.objects.filter(role=new).update(role=old)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organizationmember_role'),
    ]

    operations = [
        migrations.RunPython(lowercase_roles, uppercase_roles),
    ]
