# Generated by Django 5.2.11 on 2026-03-01 06:12

from django.db import migrations


STATUS_MAP = {'ACTIVE': 'active', 'ARCHIVED': 'archived', 'DELETED': 'deleted'}
ROLE_MAP = {'ADMIN': 'admin', 'MEMBER': 'member', 'VIEWER': 'viewer'}


def lowercase_values(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    ProjectMember = apps.get_model('projects', 'ProjectMember')
    for old, new in STATUS_MAP.items():
        Project.objects.filter(status=old).update(status=new)
    for old, new in ROLE_MAP.items():
        ProjectMember.objects.filter(role=old).update(role=new)


def uppercase_values(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    ProjectMember = apps.get_model('projects', 'ProjectMember')
    for old, new in STATUS_MAP.items():
        Project.objects.filter(status=new).update(status=old)
    for old, new in ROLE_MAP.items():
        ProjectMember.objects.filter(role=new).update(role=old)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_status_alter_projectmember_role'),
    ]

    operations = [
        migrations.RunPython(lowercase_values, uppercase_values),
    ]
