# Generated by Django 5.2.11 on 2026-03-01 06:12

from django.db import migrations


ROLE_MAP = {'ADMIN': 'admin', 'MANAGER': 'manager', 'MEMBER': 'member'}


def lowercase_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for old, new in ROLE_MAP.items():
        User.objects.filter(role=old).update(role=new)


def uppercase_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for old, new in ROLE_MAP.items():
        User.objects.filter(role=new).update(role=old)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(lowercase_roles, uppercase_roles),
    ]
