# Generated by Django 5.2.11 on 2026-03-01 06:12

from django.db import migrations


STATUS_MAP = {
    'BACKLOG': 'backlog', 'TODO': 'todo', 'IN_PROGRESS': 'in_progress',
    'IN_REVIEW': 'in_review', 'DONE': 'done', 'CANCELLED': 'cancelled',
}
PRIORITY_MAP = {'CRITICAL': 'critical', 'HIGH': 'high', 'MEDIUM': 'medium', 'LOW': 'low'}
ACTION_MAP = {
    'CREATED': 'created', 'UPDATED': 'updated', 'STATUS_CHANGED': 'status_changed',
    'PRIORITY_CHANGED': 'priority_changed', 'ASSIGNED': 'assigned',
    'UNASSIGNED': 'unassigned', 'COMMENTED': 'commented',
    'ATTACHMENT_ADDED': 'attachment_added', 'ATTACHMENT_REMOVED': 'attachment_removed',
    'MOVED': 'moved', 'DELETED': 'deleted', 'RESTORED': 'restored',
}


def lowercase_values(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    ActivityLog = apps.get_model('tasks', 'ActivityLog')
    for old, new in STATUS_MAP.items():
        Task.objects.filter(status=old).update(status=new)
    for old, new in PRIORITY_MAP.items():
        Task.objects.filter(priority=old).update(priority=new)
    for old, new in ACTION_MAP.items():
        ActivityLog.objects.filter(action=old).update(action=new)


def uppercase_values(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    ActivityLog = apps.get_model('tasks', 'ActivityLog')
    for old, new in STATUS_MAP.items():
        Task.objects.filter(status=new).update(status=old)
    for old, new in PRIORITY_MAP.items():
        Task.objects.filter(priority=new).update(priority=old)
    for old, new in ACTION_MAP.items():
        ActivityLog.objects.filter(action=new).update(action=old)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_activitylog_action_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.RunPython(lowercase_values, uppercase_values),
    ]
